server:
  port: 9090

spring:
  application:
    name: suxia-dream

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  redis:
    key-prefix: his
    #数据库索引
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 10000
    jedis:
      pool:
        #最大连接数
        max-active: -1
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 50

  datasource:
    # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    url: jdbc:mysql://127.0.0.1:3306/idb?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    # 数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 连接池名称，默认HikariPool-1
    hikari:
      pool-name: KevinHikariPool
      # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 12
      # 连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      # 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      # 连接测试查询
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


