server:
  port: 9090

spring:
  application:
    name: suxia-dream

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  redis:
    key-prefix: his
    #数据库索引
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 10000
    jedis:
      pool:
        #最大连接数
        max-active: -1
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 50


